#pragma config(Sensor, in5,    basepot,        sensorPotentiometer)
#pragma config(Sensor, in6,    liftpot,        sensorPotentiometer)
#pragma config(Sensor, in7,    manippot,       sensorPotentiometer)
#pragma config(Motor,  port1,           mogoL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motomanipR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motomanipL,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motoliftR1,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           left,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           passive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motoliftL1,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mogoR,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const unsigned short trueSpeed[128] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 21 , 21, 21, 22, 22, 22, 23, 24, 24,
	25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
	28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
	37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
	41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
	46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
	52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
	71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
	80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
	88, 89, 89, 90, 90,127,127,127
};

//LINEAR DRIVE VARIABLES
int threshold = 10;
int speedLeft;
int speedRight;
string rightDrive= "rightDrive";
string leftDrive = "leftDrive";

//SETSPEED FUNCTION

void setSpeed()
{
	if(speedLeft > 127) speedLeft = 127;
	if(speedLeft < -127) speedLeft = -127;
	if(speedRight > 127) speedRight = 127;
	if(speedRight < -127) speedRight = -127;
	int absSpeedL = trueSpeed[abs(speedLeft)]*(speedLeft/abs(speedLeft+0.0001));
	int absSpeedR = trueSpeed[abs(speedRight)]*(speedRight/abs(speedRight+0.0001));
	motor[left] = absSpeedL;
	motor[right] = absSpeedR;
}
string sound = "";
task music()
{
	playSoundFile(sound);
}
//MUSIC BY BEETHOVEN
task fifth()
{
	//  Piano Player II
	//    rest);
	wait10Msec(75);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(622,38);	wait10Msec(38);
	//    rest);
	wait10Msec(38);
	PlayTone(698,15);	wait10Msec(19);
	PlayTone(698,15);	wait10Msec(19);
	PlayTone(698,15);	wait10Msec(19);
	PlayTone(587,38);	wait10Msec(38);
	//    rest);
	wait10Msec(75);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(622,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(1244,15);	wait10Msec(19);
	PlayTone(1244,15);	wait10Msec(19);
	PlayTone(1244,15);	wait10Msec(19);
	PlayTone(1047,38);	wait10Msec(38);
	//    rest);
	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(587,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(831,15);	wait10Msec(19);
	PlayTone(784,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1175,38);	wait10Msec(38);
	//    rest);
	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(19);
	PlayTone(1175,15);	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(19);
	PlayTone(1175,15);	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1568,15);	wait10Msec(19);
	PlayTone(1397,15);	wait10Msec(19);
	PlayTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(38);
	PlayTone(1047,19);	wait10Msec(19);
	//    rest);
	wait10Msec(38);
	PlayTone(784,38);	wait10Msec(38);
	return;
}

//MUSIC OF HALL
task hall()
{
	wait10Msec(8);  // Rest
	PlayTone(220,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,24);  wait10Msec(30);
	PlayTone(311,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(311,24);  wait10Msec(30);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(233,12);  wait10Msec(15);
	PlayTone(294,24);  wait10Msec(30);
	PlayTone(220,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(392,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(392,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	PlayTone(220,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,24);  wait10Msec(30);
	PlayTone(311,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(311,24);  wait10Msec(30);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(233,12);  wait10Msec(15);
	PlayTone(294,24);  wait10Msec(30);
	PlayTone(220,12);  wait10Msec(15);
	PlayTone(247,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(294,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(392,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(262,12);  wait10Msec(15);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(392,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(370,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(523,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(523,24);  wait10Msec(30);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(370,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(523,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(523,24);  wait10Msec(30);
	PlayTone(494,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(370,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(523,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(523,24);  wait10Msec(30);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(330,12);  wait10Msec(15);
	PlayTone(370,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(494,12);  wait10Msec(15);
	PlayTone(415,12);  wait10Msec(15);
	PlayTone(494,24);  wait10Msec(30);
	PlayTone(523,12);  wait10Msec(15);
	PlayTone(440,12);  wait10Msec(15);
	PlayTone(523,24);  wait10Msec(30);
	PlayTone(494,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	wait10Msec(8);  // Rest
	PlayTone(440,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(659,24);  wait10Msec(30);
	PlayTone(622,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(622,24);  wait10Msec(30);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(466,8);  wait10Msec(15);
	PlayTone(587,24);  wait10Msec(30);
	PlayTone(440,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(880,8);  wait10Msec(15);
	PlayTone(784,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(784,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	PlayTone(440,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(659,24);  wait10Msec(30);
	PlayTone(622,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(622,24);  wait10Msec(30);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(466,8);  wait10Msec(15);
	PlayTone(587,24);  wait10Msec(30);
	PlayTone(440,8);  wait10Msec(15);
	PlayTone(494,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(587,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(523,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(880,8);  wait10Msec(15);
	PlayTone(831,8);  wait10Msec(15);
	PlayTone(659,8);  wait10Msec(15);
	PlayTone(831,8);  wait10Msec(15);
	PlayTone(988,8);  wait10Msec(15);
	PlayTone(880,48); wait10Msec(60);
	return;
}



task main()
{
	bLCDBacklight = true;
	int manippotval = 2460;//2350
	int liftpotval = 1380;
	int basepotval = 4090;
	float KpM = .07;// working .05
	float KiM = -0.0007;
	float KdM = 1.5;// working .9
	int integralM = 0;
	int pErrorM = 0;
	int mogorunning = 1;
	int manipid = 1;

	while(true)
	{
		if (vexRT[Btn7U])
		{
			sound = "finalmeme.wav";
			startTask(music);
		}
		else if (vexRT[Btn7L])
		{
			sound = "laugh.wav";
			startTask(music);
		}
		else if (vexRT[Btn7R])
		{
			startTask(fifth);
			startTask(hall);
		}
		if (vexRT[Btn7D])
		{
			stopTask(music);
			clearSounds();
			stopTask(fifth);
			stopTask(hall);
		}

		//to change whether the mogo runs by itself or not
		if (vexRT[Btn8U])
		{
			mogorunning = 1;
		}
		else if (vexRT[Btn8D])
		{
			mogorunning = 0;
		}

		//to change whteher PID for manipulator is desired or not
		if (vexRT[Btn8L])
		{
			manipid = 1;
		}
		else if (vexRT[Btn8R])
		{
			manipid = 0;
		}

		clearLCDLine(0);                                  // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		string manipVal;
		string PERROR;
		sprintf(manipVal, "manipVal:%d", SensorValue[manippot]);
		sprintf(PERROR, "manipultaorerror: %d", pErrorM);
		displayLCDString(0, 0, manipVal);
		displayLCDString(1, 0, PERROR);
		// Arcade driving control
		if (abs(vexRT[Ch3]) + abs(vexRT[Ch4]) > 12)
		{
			speedLeft = vexRT[Ch4] + vexRT[Ch3];
			speedRight = vexRT[Ch4] -  vexRT[Ch3];
		}
		else
		{
			speedLeft = 0;
			speedRight = 0;
		}
		setSpeed();

		//mogo Block
		if (vexRT[Btn5D])
		{
			motor[mogoL] = 127 * vexRT[Btn5D];
			motor[mogoR] = 127 * vexRT[Btn5D];
		}
		else if (vexRT[Btn5U] && !(SensorValue[basepot] >= basepotval))
		{
			motor[mogoL] = -127 * vexRT[Btn5U];
			motor[mogoR] = -127 * vexRT[Btn5U];
		}
		else if (SensorValue[basepot] >= basepotval && mogorunning == 1)
		{

			motor[mogoL] = -15;
			motor[mogoR] = -15;
		}
		else if (mogorunning == 0)
		{
			motor[mogoL] = -127 * vexRT[Btn5U];
			motor[mogoR] = -127 * vexRT[Btn5U];
		}
		else
		{
			motor[mogoL] = 0;
			motor[mogoR] = 0;
		}
		//	motor[mogoL] = (vexRT[Btn5U] * 127) + (vexRT[Btn5D] * -127);


		//block for potentiometer code for the lift
		if ((abs(vexRT[Ch2]) > 0 && !(SensorValue[liftpot] <= liftpotval)) || (vexRT[Ch2] > 0))
		{
			motor[motoliftL1] = vexRT[Ch2];
			motor[motoliftR1] = vexRT[Ch2];
		}

		else if (SensorValue[liftpot] <= liftpotval)
		{
			motor[motoliftL1] = 0;
			motor[motoliftR1] = 0;
		}
		// Block for Manipulator Potentiometer code.
		if ((SensorValue[manippot] >= 4080) && (vexRT[Ch1] > 0))
		{
			motor[motomanipR] = 0;
			motor[motomanipL] = 0;

		}

		else if (vexRT[Ch1]>0 || manipid == 0)
		{
			motor[motomanipL] = vexRT[Ch1];
			motor[motomanipR] = vexRT[Ch1];
			integralM = 0;
		}

		else if (vexRT[Ch1] < 0 && !(SensorValue[manippot] < manippotval) )
		{
			int error = -manippotval + SensorValue[manippot];
			if (error == 0 || abs(integralM) < 20 || integralM > 50)
			{
				integralM = 0;
			}
			else
			{
				integralM = integralM + error;
			}
			motor[motomanipL] = (int)(vexRT[Ch1]/127.0 * (error * KpM + integralM * KiM + (pErrorM-error) * KdM));
			motor[motomanipR] = (int)(vexRT[Ch1]/127.0 * (error * KpM + integralM * KiM + (pErrorM-error) * KdM));
			pErrorM = error;
		}
		else if (SensorValue[manippot] <= manippotval)
		{
			motor[motomanipR] = 0;
			motor[motomanipL] = 0;

		}




		//rest of motors operating lol
		motor[passive] = (63*vexRT[Btn6U]) + (-63 * vexRT[Btn6D]);
	}
}
