#pragma config(Motor,  port6,           moto1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           moto2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)

	{
		motor[moto1] = vexRt[ch1]
		motor[moto2] = vexRT[ch1]

	}

}
